### ISSUE TITLE
PNG image output is broken in KSP 1.4.5.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/KSP-Graphotron#12]
The error given was:

[EXC ﻿13:45:22.879] MissingMethodException: Method not found: 'UnityEngine.Texture2D.EncodeToPNG'.
    Graphotron.ModuleEnviroSensorPlotter.DrawWindowMain (Int32 windowID)
    UnityEngine.GUILayout+LayoutedWindow.DoWindow ﻿(Int32 windowID)
    UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func﻿, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style﻿﻿) ﻿

I'll need to figure out which method should be used instead.

**Comment by StoneBlue** [comment]
Ezriilc, maybe this will help.
I have it from an excellent KSP coder, that this should be what you need:

https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToPNG.html

**Comment by Ezriilc** [comment]
@StoneBlue :  Thanks very much for the input!  Sadly, I don't think I know enough to use it, but hopefully someone else does.  However, I will stare at this for a while to see if I can make sense of it.

**Comment by StoneBlue** [comment]
No problem... I cant code at all... but I often talk with peeps who do, so i asked one :P 
Hopefully someone can use the info to move forward.

**Comment by linuxgurugamer** [comment]
I just cloned the repo, compiled and ran it against 1.5.1, and it worked without a problem.

**Comment by linuxgurugamer** [comment]
Check to be sure you are compiling against .Net 3.5

**Comment by Ezriilc** [comment]
Yea, I've been compiling to .Net 3.5, which leads me to wonder what the issue may have been.

Thanks for your time!

**Comment by Ezriilc** [comment]
Recompiling against KSP v1.5.1 has fixed this.
