### ISSUE TITLE
Version file not in download

### ISSUE THREAD

**Issue by HebaruSan** [Ezriilc/KSP-Graphotron#15]
The NetKAN bot is encountering an inflation error for this mod, preventing the latest release from being added to CKAN:

![image](https://user-images.githubusercontent.com/1559108/76271583-dd7c6e00-6270-11ea-9d27-5677dc9844ac.png)

This happens because there is no .version file in the download:

- https://www.kerbaltek.com/_downloads/graphotron/Graphotron-1.5.1_for-KSP-1.9.zip

Presumably this relates to the recent folder reorganization.

**Comment by Ezriilc** [comment]
OOPS!  Fixed.  Sorry about that.
Thank YOU for the quick heads-up!

**Comment by HebaruSan** [comment]
Thanks!
