### ISSUE TITLE
Feature: Activation button or hot-key.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/KSP-Graphotron#6]
Recommended by delta wee.

To allow opening the interface without having to right-click the part.

**Comment by StoneBlue** [comment]
This one can probably be closed, as it looks like someone, probably LinuxguruGamer, added a button to the stock toolbar, in his 0.4.4 recompile.

**Comment by Ezriilc** [comment]
Oh, cool!  But... I'll need a pull request.
EDIT: Never mind.  I'm a bit thick sometimes.
